### ISSUE TITLE
Multiple schemas support

### ISSUE THREAD

**Issue by idkjs** [baransu/graphql_ppx_re#14]
Discussion and working version using multiple endpoints by 

here: https://github.com/mhallin/graphql_ppx/issues/86 and here: https://github.com/mhallin/graphql_ppx/pull/82

**Comment by idkjs** [comment]
How do we use the `rewrite` function here? https://github.com/baransu/graphql_ppx_re/blob/eca4afaa0e979cd0d43c4d92fe5322aa0856092f/src/bucklescript/graphql_ppx.re#L59

**Comment by arnarthor** [comment]
@idkjs Just wanted to point out #51. I remember you asking about bsb6 support on the old repo. When #50 is merged you'll have bsb6 support on this repo 👍

**Comment by idkjs** [comment]
@arnarthor nice follow up, boss!

**Comment by baransu** [comment]
Releases as `0.4.6`
