### ISSUE TITLE
Can't get member '__schema' of non-object type null

### ISSUE THREAD

**Issue by MargaretKrutikova** [baransu/graphql_ppx_re#30]
Graphql tools, such as `graphqurl` and `apollo-cli` generate json schema that is not wrapped in `data`, and it seems like it breaks the extension with the error:
```
Fatal error: exception Yojson.Basic.Util.Type_error("Can't get member '__schema' of non-object type null", 870828711)
File "", line 1:
Error: Error while running external preprocessor
```

In the old repo (`graphql_ppx`) there was a script `sendIntrospection.js` that generated schema in the format that worked. Why was the script removed? Is there any way to fix this issue so that it doesnt require your schema be in a different format that other graphql tools generate?

**Comment by baransu** [comment]
Thank you for pointing this out. I removed it because I wasn't using it in my project. I plan to bring it back and not require users to depend on third-party modules.

**Comment by MargaretKrutikova** [comment]
Thanks for the quick response!
I don't mind using an external dependency, since it will still end up in devDeps, but those tools generate the schema in the format which the extension doesn't understand. Maybe it is reasonable to make the extension work with the standard format of the introspection query response?

**Comment by baransu** [comment]
My current workflow I'm using is documented in https://github.com/baransu/graphql_ppx_re#usage.
I'll try to look into different tools and see what's the most common standard in the community.
