### ISSUE TITLE
Expose `makeVariables` and `makeMutation`

### ISSUE THREAD

**Issue by jfrolich** [baransu/graphql_ppx_re#33]
It would be great to have a bit more API surface to make a nicer API for consuming libraries. Sometimes you'd want to set up a mutation, and provide the variables dynamically. For instance with react-apollo a hook that returns a function that accepts variables. Because the `make` functions needs the variables, we cannot get back the data structure that includes the mutation itself and the parse function.
A workaround for now is to 

- pass the whole `make` function at the last moment and initially create an empty mutation in the hook. 
- Pass the `query` attribute and `parse` method to the hook and the `variables` attribute of `make` later.

Both not great options. I would propose a `makeVariables` function to make the variables data structure, and a `makeMutation` (better naming ideas?) that does the same thing as `make` but returns the data structure without variables. Any thoughts?

Happy to try to set up a PR for this, but interested in feedback on this first.

**Comment by jfrolich** [comment]
Related discussion in `reason-apollo-hooks`: https://github.com/Astrocoders/reason-apollo-hooks/pull/59

**Comment by baransu** [comment]
Released in `0.3.5`
