### ISSUE TITLE
"Type ... doesn't have any fields" error on GitHub GraphQL schema.

### ISSUE THREAD

**Issue by Zimmi48** [baransu/graphql_ppx_re#34]
I am using GitHub's GraphQL API. The following query worked fine with `ppx_graphql` (the `__typename` were required though) but it does not work with `graphql_ppx_re`:

```graphql
  query issueMilestone($owner: String!, $repo: String!, $number: Int!) {
    repository(owner:$owner, name:$repo) {
      issue(number:$number) {
        id
        milestone { id }
        timelineItems(itemTypes:[CLOSED_EVENT],last:1) {
          totalCount
          nodes {
            __typename
            ... on ClosedEvent {
              closer {
                __typename
                ... on PullRequest {
                  id
                  milestone { id }
                }
                ... on Commit {
                  associatedPullRequests(first: 2) {
                    nodes {
                      id
                      milestone { id }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
```

The error is:

```
Fatal error: exception Graphql_ppx_base__Schema.Invalid_type("Type IssueTimelineItems doesn't have any fields")
```

Given that it is GitHub's GraphQL schema, I am pretty confident that this is a valid schema.

Since this error looks specific to the handling of union types, I think it is the same as https://github.com/mhallin/graphql_ppx/issues/74.

Is it a bug or a known limitation? Is there a known workaround? Thanks!

**Comment by baransu** [comment]
When working with union types you only can query on cases and not on whole field. To adjust your example to `graphql_ppx_re` you only have to remove `__typename` from the union field. It's added behind scenes as it allows us to parse the result as one of the provided union cases and wrap it into a poly-variant.

Here is an example of a correct query:
```reason
module WorkingQuery = [%graphql
  {|
  query issueMilestone($owner: String!, $repo: String!, $number: Int!) {
    repository(owner:$owner, name:$repo) {
      issue(number:$number) {
        id
        milestone { id }
        timelineItems(itemTypes:[CLOSED_EVENT],last:1) {
          totalCount
          nodes {
            ... on ClosedEvent {
              closer {
                ... on PullRequest {
                  id
                  milestone { id }
                }
                ... on Commit {
                  associatedPullRequests(first: 2) {
                    nodes {
                      id
                      milestone { id }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
|}
];
```

If it doesn't solve your issue please reopen 🙂

**Comment by baransu** [comment]
@Zimmi48 Added it to the troubleshooting section in README: https://github.com/baransu/graphql_ppx_re#type--doesnt-have-any-fields

**Comment by Zimmi48** [comment]
Thank you so much for the quick answer! If this hadn't been a migration from `ppx_graphql`, I would never have manually included this `__typename` field, and I wouldn't have had any trouble :laughing:
