### ISSUE TITLE
@bsField is not removed from the query output 

### ISSUE THREAD

**Issue by MargaretKrutikova** [baransu/graphql_ppx_re#41]
I think it is the same issue as [this one](https://github.com/mhallin/graphql_ppx/issues/58) from `graphql_ppx`, and there is this unmerged [PR](https://github.com/mhallin/graphql_ppx/pull/76) which is a one-liner 😄 

Is it possible to include this quick fix? Would be really helpful!
Thanks!

Edit: I think it is [this](https://github.com/baransu/graphql_ppx_re/blob/master/src/base/graphql_printer.re#L77) block of code that can be edited to include `"bsField"`, I am not sure though what other consequences this change might have. Why is it required to have `"bsField"` when spreading multiple fragments anyway? Is it specified somewhere in the readme?

**Comment by baransu** [comment]
Fixed in `0.3.3`
