### ISSUE TITLE
Small improvement in syntax

### ISSUE THREAD

**Issue by jfrolich** [baransu/graphql_ppx_re#42]
```reason
module CreateGoalFeedItemMutation = [%graphql
  {|
    mutation CreateGoalFeedItem($goalFeedItem: CreateGoalFeedItemInput!) {
      createGoalFeedItem(goalFeedItem: $goalFeedItem) {
        id
      }
    }
|}
];
```

to:

```reason
[%graphql
  {|
    mutation CreateGoalFeedItem($goalFeedItem: CreateGoalFeedItemInput!) {
      createGoalFeedItem(goalFeedItem: $goalFeedItem) {
        id
      }
    }
|}
];
```

In other words skip the module declaration as we already have the name of the mutation and query which is not reflected in the data, so it is an ideal identifier we can use as the module name so we have less repetition. Any thoughts? Do I miss certain use cases?

**Comment by baransu** [comment]
1. Operation name is not required in GraphQL.
2. I think it’s less magical especially for newcomers when you assign result expicitly to module.

I’m against this change as it doesn’t bring any value.

**Comment by osener** [comment]
I think this would break `include [%graphql ...]` which I frequently use

**Comment by jfrolich** [comment]
Ok I wanted this idea out there. Probably not worth it :)
