### ISSUE TITLE
Can't use the library with bucklescript warning 102 enabled.

### ISSUE THREAD

**Issue by johnhaley81** [baransu/graphql_ppx_re#43]
👋 

We're using this library in a project that has the Bucklescript Warning 102 (`polymorphic comparison introduced (maybe unsafe)`) set to error and it looks like that's used in the generated code from this ppx somewhere.

So somewhere it's doing a comparison using a `==`, `>`, `<`, `<=`, or `>=` operator. I'm not sure where in the code that would be happening yet but it seems (I don't think it does at least) that a comparison like that is needed.

The above warning is very useful and I'd hate to leave it turned off. Would people be open to removing comparisons like that from the lib?

I also want to note that the original graphql_ppx` did not trigger this warning.

**Comment by baransu** [comment]
Fixed in `0.3.3`
