### ISSUE TITLE
Add changelog

### ISSUE THREAD

**Issue by nirvdrum** [baransu/graphql_ppx_re#49]
Please consider adding a changelog to the project. I think a file in the repo is friendlier than relying on GitHub's Releases functionality, but I'd even settle for that. There have been four releases in the past 8 days and it's not readily apparent what changed.

Fortunately, the project is small enough where auditing commits is an option, otherwise I wouldn't have known about the new `makeVariables` support. But reviewing commits in general to piece together the changes is a bit tedious because GitHub renders the commits in the opposite direction you'd normally want to read them.

**Comment by baransu** [comment]
Sorry for that 😅We’ll improve

**Comment by nirvdrum** [comment]
Awesome. Thank you!

**Comment by Arnarkari93** [comment]
Hi @baransu, seems like the changelog has been removed. Will you please consider adding it again?

**Comment by nirvdrum** [comment]
It looks like it was removed in 975dbdc7eecee7142df708a07a9aee00504eb548. @jfrolich was this intentional? It looks like an unrelated change that may have slipped in.

**Comment by jfrolich** [comment]
Yes I deleted it. It's still in the legacy branch. For 1.0 I'm planning to bring it back (but probably using GitHub releases)

**Comment by jfrolich** [comment]
I re-added it on the documentation website. From 1.0 forward I'll make sure to capture the changes for new releases.
