### ISSUE TITLE
No readme in npm

### ISSUE THREAD

**Issue by kamilkuz** [baransu/graphql_ppx_re#52]
In: https://www.npmjs.com/package/@baransu/graphql_ppx_re there is information: "Unable to find a readme for @baransu/graphql_ppx_re@0.4.0"
Interesting that on yarn: https://yarnpkg.com/en/package/@baransu/graphql_ppx_re it display properly.

**Comment by baransu** [comment]
It seems like npm issue. It usually happens only right after publishing but we're a few days after the latest release and it shouldn't be a case anymore. If yarn handles that correctly I don't think there is anything we can do about it.
