### ISSUE TITLE
Idea: create a PPX starter as a base fork

### ISSUE THREAD

**Issue by jfrolich** [baransu/graphql_ppx_re#62]
It's pretty tricky currently to write a new PPX because of all the tooling necessary to eventually publish it to NPM. Having a starter that people can fork with the build configuration, and github actions etc. set up would be a huge help. 

Because this repo has a pretty great set up, it would be nice if we can fork this repo and remove all graphql_ppx code but leave everything else (perhaps with a really simple dummy PPX). Then everyone can fork from that repo and pull in any improvements in the configuration or CI.

All contributions to CI + configuration is then in a reusable Repo. Any thoughs?

**Comment by baransu** [comment]
There is great https://github.com/jchavarri/hello-ppx-esy. Maybe it would be better to  contribute some of the setup created around GH Actions and have one good and documented place where people could start with their own ppxes 🙂 

/ cc @jchavarri

**Comment by jfrolich** [comment]
Ah didn't know about that one. Looks great!

**Comment by jchavarri** [comment]
@baransu Actually the `hello-ppx-esy` repo started very strongly based on `hello-reason`, but then migrated it to GH actions, and at that point `graphql_ppx_re` was a huge help to understand how to configure the whole thing properly. Thanks a lot for your work on it! 🙌 Very happy to add any contributions / improvements to `hello-ppx-esy` based on the experience gained in this repo or others.

**Comment by baransu** [comment]
@jchavarri Actually I saw you handle cache better than in `graphql_ppx_re`. I'll have to add as build times are super long right now. 🙂

**Comment by jfrolich** [comment]
@jchavarri I have some ideas for some PPX, so will definitely try this out. Too bad these PPX's are so clunky. It would be great if bsb could accept source ppxs instead of just a binary.

**Comment by jchavarri** [comment]
@jfrolich It is possible to publish and consume ppxs from source using `esy`, check the `test_bs` folder in `hello-ppx-esy`.

I just published an article that I had in the drawer for some time, which explains the approach more in depth: https://www.javierchavarri.com/when-two-worlds-collide-using-esy-to-consume-ppxs-from-source-in-bucklescript/

Totally experimental 😄 so any feedback or problems&solutions more than welcome.

**Comment by jfrolich** [comment]
Wow thanks @jchavarri that is super enlightening and helpful! Now I finally grasp the complexity of the situation. I actually think the Esy approach is pretty great! Have to see how it affect build times in CI etc., but it looks like a solution where the PPX authors have to worry a lot less about building on every platform. I will try this for an internal/experimental PPX for sure.

I wonder though if Bucklescript would also ship a native backend, it could handle source PPX's standalone.

**Comment by jchavarri** [comment]
@jfrolich Glad it helps!

> Have to see how it affect build times in CI

If CI is configured to store esy artifacts in cache between builds, the build times should not be affected. `hello-ppx-esy` builds for example (use GH actions as mentioned above) take around 1min in macOS now.

**Comment by jchavarri** [comment]
<img width="724" alt="image" src="https://user-images.githubusercontent.com/220424/72107599-f2508a00-3331-11ea-8186-778aa206df27.png">

**Comment by baransu** [comment]
@jfrolich @jchavarri I'm closing this issue for now. If anything can be done to improve the `graphql_ppx_re`, please reopen or create new issue 🙂
